run:
  concurrency: 8
linters-settings:
  lll:
    line-length: 100
  gocognit:
    min-complexity: 50
  unconvert:
  prealloc:
linters:
  enable:
    - lll
    - gocognit
    - unconvert
    - prealloc
  disable:
    - typecheck
output:
  sort-results: true